import mongoose from "mongoose";

const codeMasterSchema = new mongoose.Schema(
  {
    accountId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Account",
      required: true,
    },
    accountName: { type: String, required: true },
    masterName: { type: String, required: true },
    quality: { type: String },
    clientCode: { type: String, required: true },
    marka: { type: String },
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

codeMasterSchema.index({ accountId: 1 });
codeMasterSchema.index({ clientCode: 1 });

export default mongoose.model("CodeMaster", codeMasterSchema);
